conf_dict = {'192.168.0.61': ['terminal len 0',
                              'config t',
                              'int gi0/0',
                              'no shut',
                              'exit',
                              'exit',
                              'show ip int brie',
                              'show run int gi0/0'],
             '192.168.0.62': ['terminal len 0',
                              'config t',
                              'int lo0',
                              'ip add 10.0.0.1 255.255.255.0',
                              'int lo1',
                              'ip add 11.0.0.1 255.255.255.0',
                              'do show run int loopback0',
                              'do show run int loopback1'],
             '192.168.0.91': ['terminal len 0', 'config t', 'int gi0/3', 'no shut'],
             'csr1.test.lab': ['terminal len 0',
                               'config t',
                               'int gi0/2',
                               'no shut',
                               'ip address 2.2.2.2 255.255.255.0',
                               'exit',
                               'exit',
                               'show ip int brie',
                               'show run int gi2']}
